### ISSUE TITLE
Show more products button doesn't work

### ISSUE THREAD

**Issue by interequipment** [shellpea/advanced-elasticsuite-catalog#17] opened 2023-10-26 13:21 UTC
show more product button is not working in category pages. I can see below console error on category page.
![image](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/43515982/157c6192-52a5-4498-b8ac-45b607201698)
and get below error when I click on show more button.
![image](https://github.com/shellpea/advanced-elasticsuite-catalog/assets/43515982/7858d0f8-91f4-4975-8ef0-b5a91e9a169b)

Hyva Theme version is 1.3.2

**Comment by Eikzx** [comment] 2023-11-22 13:13
Hello @interequipment.

I ran into the same issue and found a way to temporarily fix it.
Open the file: 
vendor/shellpea/magento-advanced-elasticsuite-catalog/view/frontend/templates/configuration.phtml

Search for "this.processPageUrl" and remove it leaving only the variable "url". 
Save the file, execute via CLI magento cache:flush and reload the page.
The Button should work as intended now.
I recommend writing a patch file for this issue to prevent fixing it by hand every time you may deploy.

Greetings 
Eike

**Comment by AlexDroomer** [comment] 2023-11-28 10:43
@Eikzx thank you, I'll add a fix for this soon

**Comment by AlexDroomer** [comment] 2023-11-28 14:53
@Eikzx and @interequipment try install last version, in previous release i missed function processPageUrl, but now adds it's and is works correct
```
composer require "shellpea/magento-advanced-elasticsuite-catalog":"^1.2.4"
```

**Closed as completed** 2024-06-22 10:13 UTC
